<a href="https://colab.research.google.com/github/EvansAmarh/Scratch/blob/main/Scratch0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
inputs = [1.2, 5.1, 2.1]

weights1 = [3.1, -2.1, 8.7, 1.0]
weights2 = [1.1, 2.1, -1.3, 3.0]
weights3 = [0.1, 2.1, 1.7, -1.0]

bias1 = 3
bias2 = 3
bias3 = 0.5

output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + bias1,
inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + bias2,
inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + bias3]
print(output)

[14.280000000000001, 12.299999999999999, 14.899999999999999]


In [ ]:
inputs = [1.2, 5.1, 2.1]

weights = [[3.1, -2.1, 8.7, 1.0], [1.1, 2.1, -1.3, 3.0], [0.1, 2.1, 1.7, -1.0]]

biases = [2, 3, 0.5]

some_value = -0.5
weight = 0.7
bias = 0.7

print(some_value*weight)
print(some_value+bias)

'''layer_outputs = [] # Output of current layer
for neuron_weights, neuron_bias in zip(weights, biases):
  neuron_output = 0 # Output of given neuron
  for n_input, weight in zip(inputs, neuron_weights):
    neuron_output += n_input*weight
  neuron_output += neuron_bias
  layer_outputs.append(neuron_output)

print(layer_outputs)'''

-0.35
0.19999999999999996


'layer_outputs = [] # Output of current layer\nfor neuron_weights, neuron_bias in zip(weights, biases):\n  neuron_output = 0 # Output of given neuron\n  for n_input, weight in zip(inputs, neuron_weights):\n    neuron_output += n_input*weight\n  neuron_output += neuron_bias\n  layer_outputs.append(neuron_output)\n\nprint(layer_outputs)'

In [ ]:
import numpy as np

inputs = [1.2, 5.1, 2.1]
weights = [[3.1, -2.1, 8.7], [1.1, 2.1, -1.3], [0.1, 2.1, 1.7]] # Updated weights to match input shape
biases = [2, 3, 0.5] # Using biases from previous cell

output = np.dot(inputs, np.array(weights).T) + biases # Transpose weights to align shapes
print(output)

[13.28 12.3  14.9 ]


In [ ]:
import numpy as np

inputs = [[1.2, 5.1, 2.1], [0.2, 2.1, 2.2,], [-1.5, 5.1, -2.3]]
weights = [[3.1, -2.1, 8.7], [1.1, 2.1, -1.3], [0.1, 2.1, 1.7]] # Updated weights to match input shape
biases = [2, 3, 0.5] # Using biases from previous cell

output = np.dot(weights, inputs) + biases # Transpose weights to align shapes
print(output)

[[-7.750e+00  5.877e+01 -1.762e+01]
 [ 5.690e+00  6.390e+00  1.042e+01]
 [-1.000e-02  1.659e+01  1.420e+00]]


In [ ]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

X = [[1, 2, 3, 2.5], [-1.5, 2.7, 3.3, -0.8]]

X, y = spiral_data(100, 3)

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

class Activation_Relu:
  def forward(self, inputs):
    self.output = np.maximum(0, inputs)

layer1 = Layer_Dense(2, 4)
activation1 = Activation_ReLU()

layer1.forward(X)
# print(layer1.output)
activation1.forward(layer1.output)
print(activation1.output)

[[ 0.70921061 -0.00184155  0.44207036  0.71351851]
 [ 0.14468757 -0.1981251   0.12173849  0.07621588]]


In [ ]:
import math

layer_outputs = [4.8, 1.21, 2.385]
E = math.e

exp_values = []

for output in layer_outputs:
  exp_values.append(E**output)

print(exp_values)

norm_base = sum(exp_values)
norm_values = []

for value in exp_values:
  norm_values.append(value / norm_base)

print(norm_values)
print(sum(norm_values))

In [ ]:
import numpy as np
import nnfs

layer_outputs = [[4.8, 1.21, 2.385], [8.9, -1.81, 0.2], [1.41, 1.051, 0.026]]

exp_values = np.exp(layer_outputs)

norm_values = exp_values / np.sum(exp_values, axis=1, keepdims=True)
print(norm_values)



In [ ]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()



X, y = spiral_data(100, 3)

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

class Activation_Relu:
  def forward(self, inputs):
    self.output = np.maximum(0, inputs)

class Activation_Softmax:
  def forward(self, inputs):
    exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
    probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
    self.output = probabilities

class Loss:
  def calculate(self, output, y):
    sample_losses = self.forward(output, y)
    data_loss = np.mean(sample_losses)
    return data_loss

class Loss_CategorivalCrossEntropy(Loss):
  def forward(self, y_pred, y_true):
    samples = len(y_pred)
    y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)

    if len(y_true.shape) == 1:
      correct_confidences = y_pred_clipped[range(samples), y_true]
    elif len(y_true.shape) == 2:
      correct_confidences = np.sum(y_pred_clipped*y_true, axis=1)

    negative_log_likelihoods = -np.log(correct_confidences)
    return negative_log_likelihoods

X, y = spiral_data(samples=100, classes=3)

dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

dense1 = Layer_Dense(3,3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

print(activation2.output[:5])

loss_function = Loss_CategoricalCrossEntropy()
loss = loss_function.calculate(activation2.output, y)

print("Loss:", loss)


In [ ]:
import math

softmax_output = [0.7, 0.1, 0.2]
target_output = [1, 0, 0]

loss = -(math.log(softmax_output[0])*target_output[0] +
         math.log(softmax_output[1])*target_output[1] +
         math.log(softmax_output[2])*target_output[2])
print(loss)

loss = -math.log(softmax_output[0])
print(loss)

In [ ]:
import numpy as np

softmax_outputs = np.array([[0.7, 0.1, 0.2],
                            [0.1, 0.5, 0.4],
                            [0.02, 0.9, 0.08]])
class_targets = [0, 1, 1]

print(-np.log(softmax_outputs[[0, 1, 2], class_targets]))